// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zThings = z.object({
  totalCount: z.optional(z.coerce.bigint().check(z.minimum(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }), z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })))
});

/**
 * Things described by an annotation-only member.
 */
export const zDescribed = zThings;

/**
 * Things described by the composition itself.
 */
export const zOverridden = zThings;

/**
 * ok
 */
export const zGetThingsResponse = zThings;
