// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zThings = z.object({
  totalCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { message: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { message: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * Things described by an annotation-only member.
 */
export const zDescribed = zThings;

/**
 * Things described by the composition itself.
 */
export const zOverridden = zThings;

/**
 * ok
 */
export const zGetThingsResponse = zThings;
